name: Deploy static content to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v6
        with:
          ref: 'main'

      - name: Checkout data branch
        run: |
          if git ls-remote --exit-code --heads origin data; then
            git clone --branch data --depth 1 https://github.com/${{ github.repository }}.git temp-data
            echo "DATA_BRANCH_EXISTS=true" >> $GITHUB_ENV
          else
            echo "No data branch found, skipping."
            echo "DATA_BRANCH_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Setup database files
        run: |
          mkdir -p web/data
          if [ "$DATA_BRANCH_EXISTS" = "true" ]; then
            find temp-data -name "*.db.gz" -exec cp {} web/data/ \;
            rm -rf temp-data
          fi

      - name: Disable Jekyll
        run: touch .nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

